Default: &defaults
  host: "*4" # any IPv4 host
  port: 3110
  approot: "http://localhost:3110"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://visualizer.upopple.com"
  <<: *defaults
